### ISSUE TITLE
Log Search panel

### ISSUE THREAD

**Issue by zeppaman** [arduosoft/RawCMS#74]
## User story
Add a log search panel to seach into logs

## task
- [ ] Add a new menu entry on the left menu called 'Logs'.
- [ ] Link the previous entry to a new view
- [ ] The view should show an input box with a search button on top and a text area or similar on the rest of the page. The user can input the search text in the box and click on the button. The results will be shown on the text area below.
- [ ] Improve documentation of FullText plugin (https://github.com/arduosoft/RawCMS/blob/master/docs/FullText.md)

## acceptance criteria
On button click, the FE app should invoke the API to search log (see https://github.com/arduosoft/RawCMS/blob/master/docs/FullText.md). Results should be shown on a text area below. Documentation of Full Text plugin should properly explain how to invoke the API and how this new FE view is done.
